import type { NextPage } from 'next'
import Head from 'next/head'
import { ReactElement } from 'react'

// Components
import { TheHeaderComponent } from '../components/TheHeader'
import { FilterPanelComponent } from '../components/FilterPanel'



const HomePage: NextPage = (): ReactElement => {
  return (
    <div>
      <Head>
        <title>Job listing</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TheHeaderComponent />
      <main className='container'>
        <FilterPanelComponent />
      </main>

      <footer></footer>
    </div>
  );
}

export default HomePage
