import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { ReactElement } from 'react';
// Components
import {
  TheHeaderComponent,
  FilterPanelComponent,
  JobListComponent,
} from '../components';
// Other
import { addPositions } from '../bus/positions/position-slice';

// import data from '../../data/data.json';
import { wrapper } from '../store';
import { IDataType } from '../types';
import axios from 'axios';

const HomePage: NextPage = (): ReactElement => {
  return (
    <div>
      <Head>
        <title>Job listing</title>
        <meta name = 'description' content = 'Generated by create next app' />
        <link rel = 'icon' href = '/favicon.ico' />
      </Head>
      <TheHeaderComponent />
      <main className = 'container'>
        <FilterPanelComponent />
        <JobListComponent />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async () => {
    const { data } = await axios.get<IDataType[]>(`http://localhost:3004/api`);

    store.dispatch(addPositions(data));
    return {
      props: {},
    };
  });

export default HomePage;
